### ISSUE TITLE
Search field placeholder not translated

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert_blog#3]
Display "Search for…" 😉

**Comment by pyrog** [comment]
In https://blog.caresteouvert.fr/
* "Read more"

In a blog post i.e. https://blog.caresteouvert.fr/contributeurs-openstreetmap-comment-traiter-les-notes-caresteouvert/
* "0 Comments"
* "Leave a Comment"

Also the form:
* "Comment*"
* "Name*"
* "E-mail*"
* "Website"
* "Post comment"

**Comment by francois2metz** [comment]
Closing as we will not use wordpress anymore.

**Comment by pyrog** [comment]
OK. Does the new blog is already in production ?
